spring.application.name=Climalert

clima.localidad.id=ciudad-autonoma-de-buenos-aires-centro
clima.localidad.nombre=Ciudad Autonoma de Buenos Aires Centro
# Obtenido de wikipedia
clima.localidad.latitud=-34.599722
clima.localidad.longitud=-58.381944

weather-api.apiKey=Clave
weather-api.baseUrl=https://api.weatherapi.com/v1